services:
  postgres:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'mydatabase'
      POSTGRES_PASSWORD: 'secret'
      POSTGRES_USER: 'myuser'
    ports:
      - '5432:5432'
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'mydatabase'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secret'
    ports:
      - '3306:3306'
